[FileDialog]
history=file:///home/user01/Public/davinci/john-doe-bad-day/other stuff/FX Elements - Muzzle Flash - Side - 001, file:///home/user01/Public/davinci/john-doe-bad-day/other stuff/FX Elements - Muzzle Flash - Front - 010, file:///home/user01/Crap/temp/root/PHOTOS FROM THE SHOP, file:///home/user01/Public/davinci/john-doe-bad-day/other stuff, file:///opt/resolve, file:///usr/lib
lastVisited=file:///usr/lib
qtVersion=6.8.0
shortcuts=file:///home/user01, file:///home/user01/Documents, file:///home/user01/Desktop, file:///home/user01/Downloads, file:mods
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)"
viewMode=Detail
