[headsetview]
height=149
maximized=false
width=299
x=1712
y=533

[steamvrstatus]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\ar\0\0\x1\xd2\0\0\b\xda\0\0\x2i\0\0\ar\0\0\x1\xd2\0\0\b\xda\0\0\x2i\0\0\0\x1\0\0\0\0\a\x80)
visible=true
